### ISSUE TITLE
Need to access documentation for this plugin 

### ISSUE THREAD

**Issue by CarlasHub** [aazztech/directorist#58]
Can someone guide me on how to access the docs for this plugin? When I try to access https://directorist.com/documentation/ I get this error:
![image](https://user-images.githubusercontent.com/34892979/82216522-f6f50280-9910-11ea-88aa-eb2853b1e1a7.png)

**Comment by kowsar89** [comment]
It's working fine now

**Comment by CarlasHub** [comment]
It's not
[image: image.png]

**Comment by CarlasHub** [comment]
Still down 
![image](https://user-images.githubusercontent.com/34892979/82343911-50316480-99eb-11ea-9071-2b127c1c9f27.png)

**Comment by kowsar89** [comment]
There are some server issues in our website our team is trying to fix. Rest assured, we'll fix it as soon as possible(if not fixed already). Please have some patience since the issue is temporary. For further queries you can email us at support@aazztech.com since GitHub is not our official support system
